routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::namespace('Profissional')->group(function () {
        Route::get('profissionais/datatables', 'ProfissionalController@dataTable')->name('profissionais.dataTable');

        Route::resource('profissionais', 'ProfissionalController');
    });

    Route::get('estabelecimentos/datatables', 'EstabelecimentoController@dataTable')->name('estabelecimentos.dataTable');

    Route::resource('estabelecimentos', 'EstabelecimentoController');

    Route::resource('unidades', 'UnidadeController');
});
Route::get('csv', function () {
    $csv = \League\Csv\Reader::createFromPath(public_path('assets/Prestadores.csv'));
    $csv->setDelimiter('#');
    $csv->setHeaderOffset(0);
    $records = $csv->getRecords();
//	dd($csv);
    $profissional = new \Painel\Models\Profissional();
//	$record = new \Illuminate\Support\Collection($record);
    foreach ($records as $record) {
        $record['cpf'] = str_replace(['-', '.', ','], "", $record['cpf']);

        if (strlen($record['cpf']) > 11 || $record['cpf'] == "") {
            $record['cpf'] = null;
        }
        //Abrevia penúltimo ou antepenúltimo sobrenome

        while (strlen($record['nome']) > 60) {

            $nome = explode(" ", $record['nome']);
            $p = 1;

            if (strlen($nome[$p]) > 3) {
                $nome[$p] = substr($nome[$p], 0, 1) . ".";
            }

        }


        if ($record['sexo'] != "m" && $record['sexo'] != "f") {

            $record['sexo'] = null;
        }

        $profissional->cpf = $record['cpf'];
        $profissional->nome = $record['nome'];
        $profissional->sexo = $record['sexo'];
        $profissional->sobre = $record['sobre'];
        $profissional->save();
    }
    echo "Fim";
});
*/

Route::get('/', function () {
    return view('index');
});

app/Models/Estabelecimento.php
<?php

namespace Painel\Models;

use Illuminate\Database\Eloquent\Model;
use Yajra\DataTables\DataTables;

class Estabelecimento extends Model
{
    protected $table = 'estabelecimentos';
    protected $fillable = [ 'nome_fan', 'razao_soc', 'cnpj', 'matriz_id' ];
    protected $dates = [ 'created_at', 'updated_at', 'deleted_at' ];

    public function tipos()
    {
        return $this->belongsToMany( 'Painel\Models\Tipo' )->select( [ 'tipos.id', 'tipos.nome' ] );
    }

    public function unidades()
    {
        return $this->hasMany( 'Painel\Models\Unidade' );
    }

    public function datatables()
    {
        return DataTables::of( $this->query()
            ->select( [ 'estabelecimentos.id', 'estabelecimentos.nome_fan', 'estabelecimentos.cnpj', 'estabelecimentos.razao_soc', 'estabelecimentos.created_at', 'estabelecimentos.updated_at' ] )
        )
            ->editColumn( 'created_at', function ( $estabelecimentos ) {
                return [
                    'display'   => e(
                        $estabelecimentos->created_at->diffForHumans()
                    ),
                    'timestamp' => $estabelecimentos->created_at->timestamp,
                ];
            } )
            ->filterColumn( 'created_at', function ( $query, $keyword ) {
                $query->whereRaw( "DATE_FORMAT(estabelecimentos.created_at,'%m/%d/%Y') LIKE ?", [ "%$keyword%" ] );
            } )->editColumn( 'updated_at', function ( $estabelecimentos ) {
                return [
                    'display'   => e(
                        $estabelecimentos->created_at->diffForHumans()
                    ),
                    'timestamp' => $estabelecimentos->created_at->timestamp,
                ];
            } )
            ->filterColumn( 'updated_at', function ( $query, $keyword ) {
                $query->whereRaw( "DATE_FORMAT(estabelecimentos.created_at,'%m/%d/%Y') LIKE ?", [ "%$keyword%" ] );
            } )
            ->make( true );
    }
}

app/Http/Controllers/Estabelecimento/EstabelecimentoTiposController.php
<?php

namespace Painel\Http\Controllers\Estabelecimento;

use Illuminate\Http\Request;
use Painel\Http\Controllers\Controller;
use Painel\Models\Estabelecimento;
use Painel\Models\Tipo;
use Whoops\Exception\ErrorException;

class EstabelecimentoTiposController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Estabelecimento $estabelecimento, Tipo $tipo)
    {
        return response()->json(['estabelecimento_tipos' => $estabelecimento->tipos], 200);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Estabelecimento $estabelecimento, Tipo $tipo, Request $request)
    {
        try {
            //TODO: Melhorar este trecho, recebendo apenas ID já seria uma boa ideia
            /*
             * $tipo_list = $tipo->whereIn... é necessário para não haver injeção de dados vindos do front
             * Ex: algum ID que não esteja armazenado como Tipo de Estabelecimento...
             */
            $tipo_list = $tipo->whereIn('id',array_column($request->toArray(),'id'))->pluck('id');

            $estabelecimento->tipos()->sync($tipo_list);
            return response()->json(true,200);
        } catch (ErrorException $e) {
            return response()->json(['error' => $e->getMessage()], 400);
        }
    }

}

app/Http/Controllers/Estabelecimento/ProcedimentoController.php
<?php

namespace Painel\Http\Controllers\Estabelecimento;

use Painel\Models\Procedimento;
use Illuminate\Http\Request;
use Painel\Http\Controllers\Controller;

class ProcedimentoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \Painel\Models\Procedimento  $procedimento
     * @return \Illuminate\Http\Response
     */
    public function show(Procedimento $procedimento)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Painel\Models\Procedimento  $procedimento
     * @return \Illuminate\Http\Response
     */
    public function edit(Procedimento $procedimento)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Painel\Models\Procedimento  $procedimento
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Procedimento $procedimento)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Painel\Models\Procedimento  $procedimento
     * @return \Illuminate\Http\Response
     */
    public function destroy(Procedimento $procedimento)
    {
        //
    }
}

app/Http/Controllers/Estabelecimento/TipoController.php
<?php

namespace Painel\Http\Controllers\Estabelecimento;

use Illuminate\Http\Request;
use Painel\Http\Controllers\Controller;
use Painel\Models\Tipo;

class TipoController extends Controller
{
    protected $model;

    /**
     * TipoController constructor.
     * @param \Painel\Models\Tipo $model
     */
    public function __construct(Tipo $model)
    {
        $this->model = $model;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response()->json(['tipos' => $this->model->latest()->get(['nome','id']), 200]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tipo = $this->model->create($request);
        return response()->json(['tipo' => $tipo, 200]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/EstabelecimentoController.php
<?php

namespace Painel\Http\Controllers;

use Painel\Models\Estabelecimento;
use Illuminate\Http\Request;
use Painel\Models\Tipo;
use Painel\Models\Unidade;
use Whoops\Exception\ErrorException;

class EstabelecimentoController extends Controller
{
    protected $model, $tipoModel, $unidadeModel;

    /**
     * EstabelecimentoController constructor.
     *
     * @param \Painel\Models\Estabelecimento $model
     */
    public function __construct(Estabelecimento $model, Tipo $tipo, Unidade $unidade)
    {
        $this->model = $model;
        $this->tipoModel = $tipo;
        $this->unidadeModel = $unidade;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('estabelecimentos.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory
     */
    public function create()
    {

        return view('estabelecimentos.create')
            ->with(['tipos' => $this->tipoModel->pluck('nome', 'id')]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $estabelecimento = $this->model->create($request->input());
        $estabelecimento->tipos()->attach($request->tipos);

        return redirect()->route('estabelecimentos.show', $estabelecimento->id);
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Contracts\View\Factory
     */
    public function show($id)
    {
        if (request()->wantsJson()) {
            $estabelecimento = $this->model->with([
                'tipos',
            ])
                ->findOrFail($id);
            return response()->json(['estabelecimento' => $estabelecimento], 200);
        }
        return view('estabelecimentos.show');
//        return view( 'estabelecimentos.show' )->with(
//            [
//                'estabelecimento' => $this->model
//                    ->with( [
//                        'tipos',
//                        'unidades.profissionais',
//                    ] )
//                    ->findOrFail( $id )
//            ]
//        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Painel\Models\Estabelecimento $estabelecimento
     *
     * @return \Illuminate\Contracts\View\Factory
     */
    public function edit($id)
    {
        return view('estabelecimentos.edit')->with(
            [
                'estabelecimento' => $this->model->findOrFail($id),
                'tipos'           => $this->tipoModel->pluck('nome', 'id'),
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Painel\Models\Estabelecimento $estabelecimento
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Estabelecimento $estabelecimento, Request $request)
    {
        try {
            $estabelecimento
                ->fill($request->input())
                ->save();
            return response()->json(['estabelecimento' => $estabelecimento], 200);
        } catch (ErrorException $e) {
            return response()->json(['error' => $e->getMessage()], 400);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Painel\Models\Estabelecimento $estabelecimento
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Estabelecimento $estabelecimento)
    {
        //
    }

    public function dataTable()
    {
        return $this->model->datatables();
    }
}

resources/views/estabelecimentos/create.blade.php
@extends('layouts.blank')
@section('title', 'Adicionar Estabelecimento')
@section('main_container')
    <div class="right_col" role="main" style="min-height: 1164px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Estabelecimento - Adicionar</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Dados da Empresa</h2>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">

                            {{-- FORM --}}
                            {{Form::open(['route' => 'estabelecimentos.store','class'=>'form-horizontal form-label-left','files' => true, 'method'=>'post'])}}

                            <div class="col-md-9 col-sm-8 col-xs-12">
                                <div class="form-group">

                                    {{Form::label('cnpj','CNPJ')}}
                                    {{Form::text('cnpj',old('cnpj'),['class'=>'form-control'])}}
                                </div>

                                <div class="form-group">

                                    {{Form::label('razao_soc','Razão Social')}}
                                    {{Form::text('razao_soc',old('razao_soc'),['class'=>'form-control'])}}
                                </div>
                                <div class="form-group">

                                    {{Form::label('nome_fan','Nome Fantasia')}}
                                    {{Form::text('nome_fan',old('nome_fan'),['class'=>'form-control'])}}
                                </div>
                                <div class="form-group">

                                    {{Form::label('tipo','Tipo(s) de Estabelecimento')}}
                                    {{Form::select('tipos[]',$tipos,old('tipos'),['id'=>'tipos','multiple'=>"multiple",'style'=>'width: 100%;'])}}
                                </div>
                            </div>

                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="ln_solid"></div>
                                {{Form::submit('Salvar',['class'=>'btn btn-success'])}}
                            </div>
                            {{Form::close()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@push('stylesheets')
    <link rel="stylesheet" href="{{asset('assets/css/forms.css')}}">
@endpush
@push('scripts')
<script src="{{asset('assets/js/forms.js')}}"></script>
<script type="text/javascript">
    $("#tipos").select2({
        language: "pt-br"
    });
</script>
@endpush

resources/views/estabelecimentos/edit.blade.php
@extends('layouts.blank')
@section('title', 'Editar Estabelecimento')
@section('main_container')
    <div class="right_col" role="main" style="min-height: 1164px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Estabelecimento - Editar</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Dados da Empresa</h2>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">

                            {{-- FORM --}}
                            {{Form::model($estabelecimento, ['route' => ['estabelecimentos.update', $estabelecimento->id], 'method' => 'patch'])}}
                            {{--{{Form::open(['route' => ['estabelecimentos.update',$estabelecimento->cnpj],'class'=>'form-horizontal form-label-left','files' => true, 'method'=>'post'])}}--}}

                            <div class="col-md-9 col-sm-8 col-xs-12">
                                <div class="form-group">

                                    {{Form::label('cnpj','CNPJ')}}
                                    {{Form::text('cnpj',old('cnpj'),['class'=>'form-control'])}}
                                </div>

                                <div class="form-group">

                                    {{Form::label('razao_soc','Razão Social')}}
                                    {{Form::text('razao_soc',old('razao_soc'),['class'=>'form-control'])}}
                                </div>
                                <div class="form-group">

                                    {{Form::label('nome_fan','Nome Fantasia')}}
                                    {{Form::text('nome_fan',old('nome_fan'),['class'=>'form-control'])}}
                                </div>

                                <div class="form-group">

                                    {{Form::label('tipo','Tipo(s) de Estabelecimento')}}
                                    {{Form::select('tipos[]', $tipos, $estabelecimento->tipos, ['id'=>'tipos','multiple'=>"multiple",'style'=>'width: 100%;'])}}
                                </div>

                                <estabelecimento-unidades></estabelecimento-unidades>

                            </div>

                            <div class="col-md-12 col-sm-12 col-xs-12">

                                <div class="ln_solid"></div>
                                {{Form::submit('Salvar',['class'=>'btn btn-success'])}}
                            </div>
                            {{Form::close()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@push('stylesheets')
    <link rel="stylesheet" href="{{asset('assets/css/forms.css')}}">
@endpush
@push('scripts')
    <script src="{{asset('assets/js/forms.js')}}"></script>
    <script type="text/javascript">
        $("#tipos").select2({
            language: "pt-BR"
        });
        //        $("#unidades").select2({
        //            language: "pt-BR"
        //        });
    </script>
@endpush

resources/views/estabelecimentos/show.blade.php
@extends('layouts.blank')
@section('title','Estabelecimentos')
@section('main_container')
<estabelecimento></estabelecimento>
@stop
{{--@section('main_container')--}}
{{--<div class="right_col" role="main" style="min-height: 1164px;">--}}
{{--<div class="">--}}
{{--<div class="page-title">--}}
{{--<div class="title_left">--}}
{{--<h3>Estabelecimento</h3>--}}
{{--</div>--}}
{{--</div>--}}

{{--<div class="clearfix"></div>--}}

{{--<div class="row">--}}
{{--<div class="col-md-12 col-sm-12 col-xs-12">--}}
{{--<div class="x_panel">--}}
{{--<div class="x_title">--}}
{{--<h2>{{$estabelecimento->nome_fan}}--}}
{{--<small>{{$estabelecimento->cnpj}}</small>--}}
{{--</h2>--}}
{{--<ul class="nav navbar-right panel_toolbox">--}}
{{--<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>--}}
{{--<li><a href="{{route('estabelecimentos.edit',$estabelecimento->id)}}"><i--}}
{{--class="fa fa-wrench"></i></a></li>--}}
{{--</ul>--}}
{{--<div class="clearfix"></div>--}}
{{--</div>--}}
{{--<div class="x_content">--}}
{{--<div class="col-md-9 col-sm-8 col-xs-12">--}}
{{--<div class="row">--}}
{{--<div class="col-md-6 col-xs-12">--}}
{{--<dl>--}}
{{--<dt>Razão Social</dt>--}}
{{--<dd>{{$estabelecimento->razao_soc}}</dd>--}}
{{--</dl>--}}
{{--</div>--}}
{{--<div class="col-md-6 col-xs-12">--}}
{{--<dl>--}}
{{--<dt>CNPJ</dt>--}}
{{--<dd>{{$estabelecimento->cnpj}}</dd>--}}
{{--</dl>--}}
{{--</div>--}}
{{--<div class="col-md-6 col-xs-12">--}}
{{--<dl>--}}
{{--<dt>Nome Fantasia</dt>--}}
{{--<dd>{{$estabelecimento->nome_fan}}</dd>--}}
{{--</dl>--}}
{{--</div>--}}
{{--<div class="col-md-6 col-xs-12">--}}
{{--<dl>--}}
{{--<dt>Tipo</dt>--}}
{{--@foreach($estabelecimento->tipos as $tipo)--}}
{{--<span class="label label-primary">{{$tipo->nome}}</span>--}}
{{--@endforeach--}}
{{--</dl>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--AVATAR--}}
{{--<div class="col-md-3 col-sm-4 col-xs-12 profile_left">--}}
{{--<div class="profile_img">--}}
{{--<div id="crop-avatar">--}}
{{--<!-- Current avatar -->--}}
{{--<img class="img-responsive avatar-view"--}}
{{--src="/storage/images/avatars/{{$estabelecimento->cnpj}}"--}}
{{--alt="Avatar"--}}
{{--title="{{$estabelecimento->nome_fan}}">--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--Especialidades--}}
{{--<div class="col-md-6 col-sm-12 col-xs-12">--}}
{{--<h2 class="page-header">--}}
{{--Unidades--}}
{{--<ul class="nav navbar-right panel_toolbox">--}}
{{--<li>--}}
{{--<a href="#" class="" data-toggle="modal" data-target=".bs-example-modal-sm">--}}
{{--<i class="fa fa-plus"></i>--}}
{{--</a>--}}
{{--</li>--}}
{{--</ul>--}}
{{--</h2>--}}

{{--@foreach($estabelecimento->unidades as $unidade)--}}
{{--<a href="{{route('unidades.show',$unidade->id)}}">--}}
{{--<span class="label label-default">{{$unidade->nome}}</span>--}}
{{--</a>--}}
{{--@endforeach--}}

{{--<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog"--}}
{{--aria-hidden="true" style="display: none;">--}}
{{--<div class="modal-dialog modal-sm">--}}
{{--<div class="modal-content">--}}

{{--<div class="modal-header">--}}
{{--<button type="button" class="close" data-dismiss="modal"--}}
{{--aria-label="Close"><span aria-hidden="true">×</span>--}}
{{--</button>--}}
{{--<h4 class="modal-title" id="myModalLabel2">Adicionar Unidade</h4>--}}
{{--</div>--}}
{{-- FORM --}}
{{--{{Form::open(['route' => 'unidades.store','class'=>'form-horizontal form-label-left','files' => true, 'method'=>'post'])}}--}}
{{--{{Form::hidden('estabelecimento_id',$estabelecimento->id)}}--}}
{{--<div class="modal-body">--}}
{{--<div class="form-group">--}}

{{--{{Form::label('nome','Nome')}}--}}
{{--{{Form::text('nome',old('nome'),['class'=>'form-control','placeholder'=>'Ex: Águas Claras'])}}--}}
{{--</div>--}}
{{--</div>--}}
{{--<div class="modal-footer">--}}
{{--<button type="button" class="btn btn-default" data-dismiss="modal">--}}
{{--Close--}}
{{--</button>--}}
{{--{{Form::submit('Salvar',['class'=>'btn btn-success'])}}--}}
{{--</div>--}}
{{--{{Form::close()}}--}}

{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}

{{--Unidades--}}
{{--<div class="col-md-12 col-sm-12 col-xs-12">--}}
{{--<div class="x_panel">--}}
{{--<div class="x_title">--}}
{{--<h2>Unidades</h2>--}}
{{--<ul class="nav navbar-right panel_toolbox">--}}
{{--<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>--}}
{{--<li><a href="{{route('estabelecimentos.edit',$estabelecimento->id)}}"><i--}}
{{--class="fa fa-wrench"></i></a></li>--}}
{{--</ul>--}}
{{--<div class="clearfix"></div>--}}
{{--</div>--}}
{{--<div class="x_content">--}}
{{--UNIDADES--}}
{{--<div class="col-md-12 col-sm-12 col-xs-12">--}}
{{--<div class="row">--}}
{{--@foreach($estabelecimento->unidades as $unidade)--}}
{{--<div class="col-md-3 col-xs-12">--}}
{{--<div class="panel panel-default">--}}
{{--<div class="panel-heading text-center">--}}
{{--<a href="{{route('unidades.show',$unidade->id)}}">--}}
{{--{{$unidade->nome}}--}}
{{--</a>--}}
{{--</div>--}}
{{--<!-- List group -->--}}
{{--<ul class="list-group text-center">--}}
{{--@forelse($unidade->profissionais as $profissional)--}}
{{--<li class="list-group-item">--}}
{{--<a href="{{route('profissionais.show',$profissional->id)}}">--}}
{{--{{$profissional->nome}}--}}
{{--</a>--}}
{{--</li>--}}
{{--@empty--}}
{{--<li class="list-group-item">--}}
{{--Não há Profissionais Vinculados.--}}
{{--<p>--}}
{{--<a href="{{route('unidades.edit',$unidade->id)}}"--}}
{{--class="label label-warning">Clique--}}
{{--aqui--}}
{{--para editar</a></p>--}}
{{--</li>--}}
{{--@endforelse--}}
{{--</ul>--}}
{{--</div>--}}
{{--</div>--}}
{{--@endforeach--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--</div>--}}
{{--@stop--}}