routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::namespace('Profissional')->group(function () {
        Route::get('profissionais/datatables', 'ProfissionalController@dataTable')->name('profissionais.dataTable');

        Route::resource('profissionais', 'ProfissionalController');
    });

    Route::get('estabelecimentos/datatables', 'EstabelecimentoController@dataTable')->name('estabelecimentos.dataTable');

    Route::resource('estabelecimentos', 'EstabelecimentoController');

    Route::resource('unidades', 'UnidadeController');
});
Route::get('csv', function () {
    $csv = \League\Csv\Reader::createFromPath(public_path('assets/Prestadores.csv'));
    $csv->setDelimiter('#');
    $csv->setHeaderOffset(0);
    $records = $csv->getRecords();
//	dd($csv);
    $profissional = new \Painel\Models\Profissional();
//	$record = new \Illuminate\Support\Collection($record);
    foreach ($records as $record) {
        $record['cpf'] = str_replace(['-', '.', ','], "", $record['cpf']);

        if (strlen($record['cpf']) > 11 || $record['cpf'] == "") {
            $record['cpf'] = null;
        }
        //Abrevia penúltimo ou antepenúltimo sobrenome

        while (strlen($record['nome']) > 60) {

            $nome = explode(" ", $record['nome']);
            $p = 1;

            if (strlen($nome[$p]) > 3) {
                $nome[$p] = substr($nome[$p], 0, 1) . ".";
            }

        }


        if ($record['sexo'] != "m" && $record['sexo'] != "f") {

            $record['sexo'] = null;
        }

        $profissional->cpf = $record['cpf'];
        $profissional->nome = $record['nome'];
        $profissional->sexo = $record['sexo'];
        $profissional->sobre = $record['sobre'];
        $profissional->save();
    }
    echo "Fim";
});
*/

Route::get('/', function () {
    return view('index');
});

resources/views/profissionais/create.blade.php
@extends('layouts.blank')
@section('title', 'Adicionar Profissional')
@section('main_container')
    <div class="right_col" role="main" style="min-height: 1164px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Profissional - Adicionar</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Dados Pessoais</h2>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">
                            <div class="row">
                                {{-- FORM --}}
                                {{Form::open(['route' => 'profissionais.store','class'=>'form-horizontal form-label-left','files' => true, 'method'=>'post'])}}

                                <div class="col-md-9 col-sm-8 col-xs-12">
                                    <div class="form-group">

                                        {{Form::label('cpf','CPF')}}
                                        {{Form::text('cpf',old('cpf'),['class'=>'form-control'])}}
                                    </div>

                                    <div class="form-group">

                                        {{Form::label('nome','Nome')}}
                                        {{Form::text('nome',old('nome'),['class'=>'form-control'])}}
                                    </div>

                                    <div class="form-group">

                                        {{Form::label('dt_nasc','Data de Nascimento')}}
                                        {{Form::date('dt_nasc',old('dt_nasc'),['class'=>'form-control'])}}
                                    </div>

                                    <div class="form-group">

                                        <div id="gender" class="btn-group" data-toggle="buttons">
                                            <label class="btn btn-default {{old('sexo') =='f'?'active':''}}"
                                                   data-toggle-class="btn-primary"
                                                   data-toggle-passive-class="btn-default">
                                                {{Form::radio('sexo','f',old('sexo') =='f'?'checked':'')}} &nbsp;
                                                Feminino &nbsp;
                                            </label>

                                            <label class="btn btn-default {{old('sexo') =='m'?'active':''}}"
                                                   data-toggle-class="btn-primary"
                                                   data-toggle-passive-class="btn-default">
                                                {{Form::radio('sexo','m',old('sexo') =='m'?'checked':'')}} &nbsp;
                                                Masculino &nbsp;
                                            </label>
                                            <br>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        {{Form::label('sobre','Sobre')}}
                                        {{Form::textarea('sobre',old('sobre'),['class'=>'form-control'])}}
                                    </div>

                                </div>

                                <div class="col-md-3 col-sm-4 col-xs-12 profile_left">
                                    <div class="profile_img">
                                        <div id="crop-avatar">
                                            <!-- Current avatar -->
                                        </div>
                                        <div class="form-group">
                                            <label for="avatar_upload">Alterar imagem do Perfil</label>
                                            <input type="file" name="avatar_upload" id="avatar_upload"
                                                   class="form-control">
                                        </div>
                                    </div>
                                </div>


                                <div class="col-md-9 col-sm-8 col-xs-12">
                                    <h2 class="page-header">Especialidades</h2>
                                    {{Form::select('especialidades[]',$especialidades,old('especialidades'),['id'=>'especialidades','multiple'=>"multiple",'style'=>'width: 100%;'])}}
                                </div>

                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="ln_solid"></div>
                                    {{Form::submit('Salvar',['class'=>'btn btn-success'])}}
                                </div>
                                {{Form::close()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@push('stylesheets')
    <link rel="stylesheet" href="{{asset('assets/css/forms.css')}}">
@endpush
@push('scripts')
    <script src="{{asset('assets/js/forms.js')}}"></script>
    <script type="text/javascript">
        $("#especialidades").select2({
            language: "pt-br"
        });
    </script>
@endpush

resources/views/profissionais/index.blade.php
@extends('layouts.blank')
@section('title','Profissionais')

@push('stylesheets')
<!-- Datatables.net -->
<link href="{{ asset("assets/css/datatables.css") }}" rel="stylesheet">
@endpush

@section('main_container')
    <div class="right_col" role="main" style="min-height: 1161px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Profissionais</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><a class="btn btn-info btn-sm" href="{{route('profissionais.create')}}">Adicionar</a>
                            </h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                       aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settings 1</a>
                                        </li>
                                        <li><a href="#">Settings 2</a>
                                        </li>
                                    </ul>
                                </li>
                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">
                            <table class="table table-bordered table-striped table-responsive" id="profissionais-table">
                                <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>CPF</th>
                                    <th>Criado em</th>
                                    <th>Última atualização</th>
                                    <th>Opções</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
    <script src="{{asset('assets/js/datatables.js')}}"></script>
    @endpush

    @push('scripts')
    <script>
        $(document).ready(function () {

            $('#profissionais-table').DataTable({
                    language: {
                        url: '/assets/datatables/Portuguese-Brasil.json'
                    },
                    dom: 'Blfrtip',
                    responsive: true,
                    lengthMenu: [[10, 50, 100], [10, 50, 100]],
                    scrollCollapse: true,
                    order: [[3, "desc"]],
                    scrollY: '54vh',
                    paging: true,
                    serverSide: true,
                    ajax: '{!! route('profissionais.dataTable') !!}',
                    rowId: 'id',
                    columns: [
                        {data: 'nome', name: 'Nome', responsivePriority: 1},
                        {data: 'cpf', name: 'CPF', responsivePriority: 2},
                        {
                            data: 'created_at',
                            type: 'num',
                            render: {
                                _: 'display',
                                sort: 'timestamp'
                            },
                            responsivePriority: 4,
                        },
                        {
                            data: 'updated_at',
                            type: 'num',
                            render: {
                                _: 'display',
                                sort: 'timestamp'
                            },
                            responsivePriority: 5
                        },
                        {
                            "defaultContent": "<button class='btn btn-sm btn-default'><i class='fa fa-folder-open'></i> Abrir</button>",
                            responsivePriority: 3
                        },
                    ],
                    /* Double click*/
                    "fnDrawCallback": function () {
                        $('#profissionais-table tbody tr').dblclick(function () {
                            var redirection = $(this).attr('id');
                            document.location.href = '{{url()->current()}}/' + redirection;
                        });

                        $('#profissionais-table tbody tr').hover(function () {
                            $(this).css('cursor', 'pointer');
                        }, function () {
                            $(this).css('cursor', 'auto');
                        });
                    },
                })
                .on('click', 'button', function () {
                    document.location.href = '{{url()->current()}}/' + $(this).parents('tr').attr('id');
                });
        });
    </script>
    @endpush
@stop

resources/views/profissionais/show.blade.php
@extends('layouts.blank')
@section('title',$profissional->nome)
@section('main_container')
    <div class="right_col" role="main" style="min-height: 1164px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Profissional</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>{{$profissional->nome}}</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="row">
                                <div class="col-md-9 col-sm-8 col-xs-12">
                                    <div class="row">
                                        <div class="col-md-4 col-xs-12">
                                            <dl>
                                                <dt>CPF</dt>
                                                <dd>
                                                    @if($profissional->cpf)
                                                        {{$profissional->cpf}}
                                                    @else
                                                        Não informado
                                                    @endif
                                                </dd>
                                            </dl>
                                        </div>
                                        <div class="col-md-4 col-xs-12">
                                            <dl>
                                                <dt>Sexo</dt>
                                                <dd>
                                                    @if($profissional->sexo == 'f')
                                                        Feminino
                                                    @else
                                                        Masculino
                                                    @endif
                                                </dd>
                                            </dl>
                                        </div>
                                        <div class="col-md-4 col-xs-12">
                                            <dl>
                                                <dt>Data de Nascimento</dt>
                                                <dd>
                                                    @if($profissional->dt_nasc)
                                                        {{$profissional->dt_nasc->format('d/m/Y')}}
                                                    @else
                                                        Não informado
                                                    @endif
                                                </dd>
                                            </dl>
                                        </div>
                                        <div class="col-xs-12">
                                            <dl>
                                                <dt>Sobre</dt>

                                                <dd>{!! nl2br(e($profissional->sobre)) !!}</dd>
                                            </dl>
                                        </div>

                                        {{--Especialidades--}}
                                        <div class="col-md-8 col-sm-12 col-xs-12">
                                            <h2 class="page-header">Especialidades</h2>
                                            @foreach($profissional->especialidades as $especialidade)
                                                <span class="label label-primary">{{$especialidade->nome}}</span>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-3 col-sm-4 col-xs-12">
                                    <div class="row">
                                        <div class="col-xs-8 col-xs-offset-2">
                                            <!-- Current avatar -->
                                            @forelse($profissional->avatar as $avatar)
                                                <a href="#" data-toggle="modal" data-target="#avatarModal">
                                                    <img class="img-rounded center-block img-thumbnail"
                                                         src="{{asset('/storage/images/avatars/'.$avatar->caminho)}}"
                                                         title="{{$profissional->nome}} - Atualizada em {{$avatar->updated_at->format('d/m/Y H:i')}}"/>
                                                </a>
                                                <!-- Modal -->
                                                <div id="avatarModal" class="modal fade" role="dialog">
                                                    <div class="modal-dialog">

                                                        <!-- Modal content-->
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close"
                                                                        data-dismiss="modal">
                                                                    &times;
                                                                </button>
                                                                <h4 class="modal-title">Foto do Perfil</h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <img class="img-rounded center-block img-thumbnail"
                                                                     src="{{asset('/storage/images/avatars/'.$avatar->caminho)}}"
                                                                     title="{{$profissional->nome}} - Atualizada em {{$avatar->updated_at->format('d/m/Y H:i')}}"/>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-default"
                                                                        data-dismiss="modal">Fechar
                                                                </button>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>
                                            @empty
                                                <img class="img-rounded center-block img-thumbnail"
                                                     src="{{asset('/assets/images/user.png')}}"
                                                     title="Foto Inexistente"/>
                                            @endforelse
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="ln_solid"></div>
                                <a href="{{route('profissionais.index')}}" class="btn btn-default btn-sm">
                                    <i class="fa fa-arrow-left"></i>
                                    Voltar
                                </a>
                                <a href="{{route('profissionais.edit',$profissional->id)}}"
                                   class="btn btn-warning btn-sm">
                                    <i class="fa fa-pencil"></i>
                                    Editar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12">
                    {{--Rede Credenciada--}}
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Rede Credenciada</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <table class="table table-striped">
                                @if(count($profissional->unidades)>0)
                                    <thead>
                                    <tr>
                                        <th>Estabelecimento</th>
                                        <th>Unidade</th>
                                    </tr>
                                    </thead>
                                @endif
                                <tbody>
                                {{--TODO adicionar botões para editar Unidade--}}
                                @forelse($profissional->unidades as $unidade)
                                    <tr>
                                        <td>
                                            <a href="{{route('estabelecimentos.show',$unidade->estabelecimento->id)}}"
                                               target="_blank">
                                                {{$unidade->estabelecimento->nome_fan}}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{route('unidades.show',$unidade->id)}}" target="_blank">
                                                {{$unidade->nome}}
                                            </a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3">
                                            Não há vínculos
                                        </td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                {{--Conselhos--}}
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Conselhos</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            @foreach($profissional->credenciais as $credencial)
                                <span class="label label-success">{{$conselhos[$credencial->conselho_id]}}
                                    : {{$credencial->registro}} - {{$credencial->uf}}</span>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop