routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::namespace('Profissional')->group(function () {
        Route::get('profissionais/datatables', 'ProfissionalController@dataTable')->name('profissionais.dataTable');

        Route::resource('profissionais', 'ProfissionalController');
    });

    Route::get('estabelecimentos/datatables', 'EstabelecimentoController@dataTable')->name('estabelecimentos.dataTable');

    Route::resource('estabelecimentos', 'EstabelecimentoController');

    Route::resource('unidades', 'UnidadeController');
});
Route::get('csv', function () {
    $csv = \League\Csv\Reader::createFromPath(public_path('assets/Prestadores.csv'));
    $csv->setDelimiter('#');
    $csv->setHeaderOffset(0);
    $records = $csv->getRecords();
//	dd($csv);
    $profissional = new \Painel\Models\Profissional();
//	$record = new \Illuminate\Support\Collection($record);
    foreach ($records as $record) {
        $record['cpf'] = str_replace(['-', '.', ','], "", $record['cpf']);

        if (strlen($record['cpf']) > 11 || $record['cpf'] == "") {
            $record['cpf'] = null;
        }
        //Abrevia penúltimo ou antepenúltimo sobrenome

        while (strlen($record['nome']) > 60) {

            $nome = explode(" ", $record['nome']);
            $p = 1;

            if (strlen($nome[$p]) > 3) {
                $nome[$p] = substr($nome[$p], 0, 1) . ".";
            }

        }


        if ($record['sexo'] != "m" && $record['sexo'] != "f") {

            $record['sexo'] = null;
        }

        $profissional->cpf = $record['cpf'];
        $profissional->nome = $record['nome'];
        $profissional->sexo = $record['sexo'];
        $profissional->sobre = $record['sobre'];
        $profissional->save();
    }
    echo "Fim";
});
*/

Route::get('/', function () {
    return view('index');
});

app/Models/Unidade.php
<?php

namespace Painel\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Unidade extends Model
{
    use SoftDeletes;

    protected $table = 'unidades';
    protected $fillable = [ 'estabelecimento_id', 'endereco_id', 'nome' ];


    public function estabelecimento()
    {
        return $this->belongsTo( 'Painel\Models\Estabelecimento' );
    }

    public function profissionais()
    {
        return $this->belongsToMany( 'Painel\Models\Profissional', 'corpo_clinico' )
            ->select( [
                'profissionais.nome',
                'profissionais.id'
            ] );
    }

    public function contatos()
    {
        return $this->belongsToMany(Contato::class,'unidade_contatos');
    }

    public function endereco()
    {
        return $this->hasOne( 'Painel\Models\Endereco', 'id', 'endereco_id' );
    }
}

app/Http/Controllers/UnidadeController.php
<?php

namespace Painel\Http\Controllers;

use Illuminate\Http\Request;
use Painel\Models\Estabelecimento;
use Painel\Models\Unidade;
use Exception;

class UnidadeController extends Controller
{
    protected $model, $estabelecimentoModel;

    /**
     * UnidadeController constructor.
     *
     * @param \Painel\Models\Unidade $model
     * @param \Painel\Models\Estabelecimento $estabelecimentoModel
     */
    public function __construct(Unidade $model, Estabelecimento $estabelecimentoModel)
    {
        $this->model = $model;
        $this->estabelecimentoModel = $estabelecimentoModel;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($estabelecimento)
    {
        try {
            if (request()->wantsJson()) {
                $unidades = $this->model->where('estabelecimento_id', '=', $estabelecimento)->get(['id', 'nome']);
                return response()->json(["lista_unidades" => $unidades], 200);
            }
            return $estabelecimento;
        } catch (Exception $e) {
            return response()->json($e, 400);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {

        $estabelecimento = $this->estabelecimentoModel->find($request->estabelecimento, ['id']);

        if ($estabelecimento) {
            return view('unidades.create')->with(['estabelecimento' => $estabelecimento]);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store($estabelecimento, Request $request)
    {
        if (request()->wantsJson()) {
            try {
                $unidade = $this->model->create([
                    'nome' => $request->nome,
                    'estabelecimento_id' => $estabelecimento,
                    'endereco_id' => $this->model->endereco()->create($request->input('endereco'))->id,
                ]);

                return response()->json($unidade, 201);

            } catch (Exception $e) {
                return response()->json($e, 400);
            }


        }

        $endereco_id = $this->model->endereco()->create($request->all())->id;

        $unidade = $this->model->create([
            'nome' => $request->nome,
            'estabelecimento_id' => $request->estabelecimento_id,
            'endereco_id' => $endereco_id,
        ]);

        return redirect()->route('unidades.show', $unidade->id);

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return $unidade
     */
    public function show($id)
    {
        if (request()->wantsJson()) {
            $unidade = $this->model->with('endereco')->findOrFail($id);
            return response()->json(['unidade' => $unidade], 200);
        }
        return view('unidades.show')->with(
            [
                'unidade' => $this->model
                    ->with([
                        'estabelecimento',
                        'profissionais.avatar',
                        'endereco',
                    ])
                    ->findOrFail($id),
            ]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Contracts\View\Factory
     */
    public
    function edit(
        $id
    )
    {

        return view('unidades.edit')->with(
            [
                'unidade' => $this->model->with
                (
                    ['profissionais', 'endereco']
                )
                    ->find($id),
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (request()->wantsJson())
        {
            try {
                $unidade = $this->model->findOrFail($id);
                $unidade->fill($request->all())->save();
                return response()->json(true, 200);
            }catch (Exception $e) {
                return response()->json("Não foi possível realizar a atualização: " . $e->getMessage(), 400);
            }
        }
        $unidade = $this->model->findOrFail($id);
        $unidade->fill($request->all())->save();
        $unidade->endereco->fill($request->all())->save();
        $unidade->profissionais()->sync($request->profissionais);

        return redirect()->route('unidades.show', $unidade->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Painel\Models\Estabelecimento $estabelecimento
     * @param  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Estabelecimento $estabelecimento, $id)
    {
        if (request()->wantsJson()) {
            return $estabelecimento->unidades($id)->delete();

        }
        // delete
        $unidade = $this->model->find($id);
        $unidade->delete();

        return redirect()->route('estabelecimentos.show', $unidade->estabelecimento_id);
    }
}

resources/views/unidades/create.blade.php
@extends('layouts.blank')
@section('title', 'Adicionar Unidade')
@section('main_container')
    <div class="right_col" role="main" style="min-height: 1164px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Adicionar Unidade - <small>{{$estabelecimento->nome_fan}}</small></h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Dados da Unidade</h2>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">

                            {{-- FORM --}}
                            {{Form::open(['route' => ['unidades.store'],'class'=>'form-horizontal form-label-left','files' => true, 'method'=>'post'])}}
                            {{Form::hidden('estabelecimento_id', $estabelecimento->id)}}
                            <div class="col-md-9 col-sm-8 col-xs-12">

                                <div class="form-group">

                                    {{Form::label('nome','Nome')}}
                                    {{Form::text('nome',old('cnpj'),['class'=>'form-control','placeholder'=>'Ex: Águas Claras'])}}
                                </div>

                                @include('forms.endereco.create')
                            </div>

                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="ln_solid"></div>
                                {{Form::submit('Salvar',['class'=>'btn btn-success'])}}
                            </div>
                            {{Form::close()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@push('stylesheets')
    <link rel="stylesheet" href="{{asset('assets/css/forms.css')}}">
@endpush
@push('scripts')
    <script src="{{asset('assets/js/forms.js')}}"></script>
    <script type="text/javascript">
        $("#especialidades").select2({
            language: "pt-br"
        });
    </script>
@endpush

resources/views/unidades/edit.blade.php
@extends('layouts.blank')
@section('title', 'Editar Unidade')
@section('main_container')
    <div class="right_col" role="main" style="min-height: 1164px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>
                        Editar Unidade
                    </h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>
                                Dados da Unidade
                                <small>
                                    (<a href="{{route('estabelecimentos.show',$unidade->estabelecimento->id)}}">
                                        {{$unidade->estabelecimento->nome_fan}}
                                    </a>)
                                </small>
                            </h2>
                            <div class="nav navbar-right panel_toolbox">
                                {{Form::open(['route'=>['unidades.destroy',$unidade->id],'method'=>'delete'])}}
                                {{Form::button('<i class="fa fa-trash"></i>',['class'=>'btn btn-danger btn-sm','type'=>'submit'])}}
                                {{Form::close()}}
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">

                            {{-- FORM --}}
                            {{Form::model($unidade, ['route' => ['unidades.update', $unidade->id], 'method' => 'patch'])}}

                            <div class="col-md-9 col-sm-8 col-xs-12">
                                <div class="form-group">

                                    {{Form::label('nome','Nome')}}
                                    {{Form::text('nome',old('nome'),['class'=>'form-control'])}}
                                </div>

                                @include('forms.endereco.edit',['endereco'=>$unidade->endereco])

                            </div>

                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <h2 class="page-header">Corpo Clínico</h2>
                                {{Form::select('profissionais[]', $unidade->profissionais->pluck('nome','id'), $unidade->profissionais, ['id'=>'profissionais','multiple'=>"multiple",'style'=>'width: 100%;','class'=>'form-control'])}}
                            </div>

                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="ln_solid"></div>
                                <a href="{{route('unidades.show',$unidade->id)}}" class="btn btn-default">
                                    <i class="fa fa-arrow-left"></i>
                                    Cancelar
                                </a>

                                {{Form::button('<i class="fa fa-save"></i> Salvar',['class'=>'btn btn-success','type'=>'submit'])}}
                            </div>
                            {{Form::close()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@push('stylesheets')
<link rel="stylesheet" href="{{asset('assets/css/forms.css')}}">
@endpush
@push('scripts')
<script src="{{asset('assets/js/forms.js')}}"></script>
<script type="text/javascript">
    $('#profissionais').select2({
        language: "pt-BR",
        minimumInputLength: 4,
        debug: true,
        ajax: {
            url: '{{route('profissionais.index')}}',
            dataType: 'json',
            delay: 250,
            processResults: function (data) {
                return {
                    results: data
                };
            },
            cache: true
        }
    });
</script>
@endpush

resources/views/unidades/index.blade.php
@extends('layouts.blank')
@section('title','Estabelecimentos')

@push('stylesheets')
<!-- Datatables.net -->
<link href="{{ asset("assets/css/datatables.css") }}" rel="stylesheet">
@endpush

@section('main_container')
    <div class="right_col" role="main" style="min-height: 1161px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Estabelecimentos</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><a class="btn btn-info btn-sm" href="{{route('estabelecimentos.create')}}">Adicionar</a></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                       aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settings 1</a>
                                        </li>
                                        <li><a href="#">Settings 2</a>
                                        </li>
                                    </ul>
                                </li>
                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>

                        <div class="x_content">
                            <table class="table table-bordered table-striped table-responsive" id="estabelecimentos-table">
                                <thead>
                                <tr>
                                    <th>Nome Fantasia</th>
                                    <th>Razão Social</th>
                                    <th>CNPJ</th>
                                    <th>Criado em</th>
                                    <th>Última atualização</th>
                                    <th>Opções</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
    <script src="{{asset('assets/js/datatables.js')}}"></script>
    @endpush

    @push('scripts')
    <script>
        $(document).ready(function () {

            $('#estabelecimentos-table')
                .DataTable({
                    language: {
                        url: '/assets/datatables/Portuguese-Brasil.json'
                    },
                    dom: 'Blfrtip',
                    responsive: true,
                    lengthMenu: [[10, 50, 100], [10, 50, 100]],
                    scrollCollapse: true,
                    order: [[3, "desc"]],
                    scrollY: '54vh',
                    paging: true,
                    serverSide: true,
                    ajax: '{!! route('estabelecimentos.dataTable') !!}',
                    rowId: 'id',
                    columns: [
                        {data: 'nome_fan', name: 'nome_fan', responsivePriority: 4},
                        {data: 'razao_soc', name: 'razao_soc', responsivePriority: 3},
                        {data: 'cnpj', name: 'CNPJ', responsivePriority: 1},
                        {
                            data: 'created_at',
                            type: 'num',
                            render: {
                                _: 'display',
                                sort: 'timestamp'
                            },
                            responsivePriority: 4,
                        },
                        {
                            data: 'updated_at',
                            type: 'num',
                            render: {
                                _: 'display',
                                sort: 'timestamp'
                            },
                            responsivePriority: 5
                        },
                        {
                            "defaultContent": "<button class='btn btn-sm btn-default'><i class='fa fa-folder-open'></i> Abrir</button>",
                            responsivePriority: 2
                        },
                    ],
                    /* Double click*/
                    "fnDrawCallback": function () {
                        $('#estabelecimentos-table tbody tr').dblclick(function () {
                            var redirection = $(this).attr('id');
                            document.location.href = '{{url()->current()}}/' + redirection;
                        }).hover(function () {
                            $(this).css('cursor', 'pointer');
                        }, function () {
                            $(this).css('cursor', 'auto');
                        });
                    },
                })
                .on('click', 'button', function () {
                    document.location.href = '{{url()->current()}}/' + $(this).parents('tr').attr('id');
                });
        });
    </script>
    @endpush
@stop

resources/views/unidades/show.blade.php
@extends('layouts.blank')
@section('title',$unidade->nome)
@section('main_container')
    <div class="right_col" role="main" style="min-height: 1164px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Unidade</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>{{$unidade->nome}}
                                <small>
                                    <a href="{{route('estabelecimentos.show',$unidade->estabelecimento->id)}}">
                                        {{$unidade->estabelecimento->nome_fan}} <i class="fa fa-external-link"></i>
                                    </a>
                                </small>
                            </h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                                <li><a href="{{route('unidades.edit',$unidade->id)}}"><i class="fa fa-wrench"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12">
                                    @if($unidade->endereco)
                                        <dl>
                                            <dd>{{$unidade->endereco->logradouro}}, {{$unidade->endereco->numero}}</dd>
                                        </dl>
                                        @if($unidade->endereco->complemento)
                                            <dl>
                                                <dt>Complemento</dt>
                                                <dd>{{$unidade->endereco->complemento}}</dd>
                                            </dl>
                                        @endif

                                        <div class="row">
                                            <div class="col-xs-6">
                                                <dl>
                                                    <dt>Bairro</dt>
                                                    <dd>{{$unidade->endereco->bairro}}</dd>
                                                </dl>
                                            </div>
                                            <div class="col-xs-6">
                                                <dl>
                                                    <dt>Cidade</dt>
                                                    <dd>{{$unidade->endereco->cidade}} - {{$unidade->endereco->uf}}</dd>
                                                </dl>
                                            </div>

                                        </div>

                                        <dl>
                                            <dt>CEP</dt>
                                            <dd>{{$unidade->endereco->cep}}</dd>
                                        </dl>
                                    @else
                                        <dl>
                                            <dt>Endereço não cadastrado.</dt>
                                        </dl>
                                    @endif
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    {{--<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4741.8520554921115!2d-48.07522358450837!3d-15.885338129431853!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935a2d36d73a8ebb%3A0xd782af7b54ffefa8!2sAde+Conjunto+6+-+Samambaia+Sul%2C+Bras%C3%ADlia+-+DF!5e1!3m2!1spt-BR!2sbr!4v1506975267261"--}}
                                    {{--width="100%" height="450" frameborder="0" style="border:0"--}}
                                    {{--allowfullscreen></iframe>--}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {{--Corpo Clínico--}}
                <div class="col-md-6 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Corpo Clínico</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settings 1</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content" style="display: block;">
                            <table class="table table-hover">
                                <tbody>
                                @forelse($unidade->profissionais as $profissional)
                                    <tr>
                                        <td>
                                            <a href="{{route('profissionais.show',$profissional->id)}}">{{$profissional->nome}}</a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td>
                                            Nao há Profissionais vinculados
                                        </td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                {{-- Contato --}}
                <contatos></contatos>
            </div>
        </div>
    </div>
    </div>
@stop