routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::namespace('Profissional')->group(function () {
        Route::get('profissionais/datatables', 'ProfissionalController@dataTable')->name('profissionais.dataTable');

        Route::resource('profissionais', 'ProfissionalController');
    });

    Route::get('estabelecimentos/datatables', 'EstabelecimentoController@dataTable')->name('estabelecimentos.dataTable');

    Route::resource('estabelecimentos', 'EstabelecimentoController');

    Route::resource('unidades', 'UnidadeController');
});
Route::get('csv', function () {
    $csv = \League\Csv\Reader::createFromPath(public_path('assets/Prestadores.csv'));
    $csv->setDelimiter('#');
    $csv->setHeaderOffset(0);
    $records = $csv->getRecords();
//	dd($csv);
    $profissional = new \Painel\Models\Profissional();
//	$record = new \Illuminate\Support\Collection($record);
    foreach ($records as $record) {
        $record['cpf'] = str_replace(['-', '.', ','], "", $record['cpf']);

        if (strlen($record['cpf']) > 11 || $record['cpf'] == "") {
            $record['cpf'] = null;
        }
        //Abrevia penúltimo ou antepenúltimo sobrenome

        while (strlen($record['nome']) > 60) {

            $nome = explode(" ", $record['nome']);
            $p = 1;

            if (strlen($nome[$p]) > 3) {
                $nome[$p] = substr($nome[$p], 0, 1) . ".";
            }

        }


        if ($record['sexo'] != "m" && $record['sexo'] != "f") {

            $record['sexo'] = null;
        }

        $profissional->cpf = $record['cpf'];
        $profissional->nome = $record['nome'];
        $profissional->sexo = $record['sexo'];
        $profissional->sobre = $record['sobre'];
        $profissional->save();
    }
    echo "Fim";
});
*/

Route::get('/', function () {
    return view('index');
});

resources/views/includes/footer.blade.php
<footer>
    <div class="pull-right">
        CLUB CARD ADMINISTRADORA DE CARTÕES DE BENEFÍCIOS E CONVÊNIOS LTDA
    </div>
    <div class="clearfix"></div>
</footer>

resources/views/includes/sidebar.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="{{ url('/') }}" class="site_title"><span>Painel Club Card</span></a>
        </div>
        
        <div class="clearfix"></div>
        
        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="{{asset('assets/images/user.png')}}" alt="Avatar of USUÁRIO" class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Olá,</span>
                <h2>{{Auth::user()->nome}}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->
        
        <br />
        
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Menu</h3>
                <ul class="nav side-menu">
                    <li><a><i class="fa fa-hospital-o"></i> Rede Credenciada <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{route('estabelecimentos.index')}}">Estabelecimentos</a></li>
                            <li><a href="{{route('profissionais.index')}}">Profissionais</a></li>
                        </ul>
                    </li>
                    {{--<li>--}}
                        {{--<a href="javascript:void(0)">--}}
                            {{--<i class="fa fa-laptop"></i>--}}
                            {{--One link--}}
                            {{--<span class="label label-success pull-right">Flag</span>--}}
                        {{--</a>--}}
                    {{--</li>--}}
                </ul>
            </div>
            {{--<div class="menu_section">--}}
                {{--<h3>Group 2</h3>--}}
                {{--<ul class="nav side-menu">--}}
                    {{--<li>--}}
                        {{--<a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>--}}
                        {{--<ul class="nav child_menu">--}}
                            {{--<li>--}}
                                {{--<a href="#">Level One</a>--}}
                                {{--<li>--}}
                                    {{--<a>Level One<span class="fa fa-chevron-down"></span></a>--}}
                                    {{--<ul class="nav child_menu">--}}
                                        {{--<li class="sub_menu">--}}
                                            {{--<a href="#">Level Two</a>--}}
                                        {{--</li>--}}
                                        {{--<li>--}}
                                            {{--<a href="#">Level Two</a>--}}
                                        {{--</li>--}}
                                        {{--<li>--}}
                                            {{--<a href="#">Level Two</a>--}}
                                        {{--</li>--}}
                                    {{--</ul>--}}
                                {{--</li>--}}
                            {{--<li>--}}
                                {{--<a href="#">Level One</a>--}}
                            {{--</li>--}}
                        {{--</ul>--}}
                    {{--</li>--}}
                {{--</ul>--}}
            {{--</div>--}}
        
        </div>
        <!-- /sidebar menu -->
        
        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{ url('/logout') }}">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

resources/views/includes/topbar.blade.php
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                       aria-expanded="false">
                        <img src="{{asset('assets/images/user.png')}}" alt="Avatar of User">
                        {{Auth::user()->nome}}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="javascript:;"> Profile</a></li>
                        <li>
                            <a href="javascript:;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url('/logout') }}"
                               onclick="event.preventDefault();
         document.getElementById('logout-form').submit();">
                                <i class="fa fa-sign-out pull-right"></i>
                                Log Out
                            </a>
                            <form id="logout-form"
                                  action="{{ url('/logout') }}"
                                  method="POST"
                                  style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </li>

                <li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown"
                       aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">6</span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                        <li>
                            <a>
                                <span class="image">
                                    <img src="{{asset('assets/images/user.png')}}" alt="Profile Image"/></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="{{asset('assets/images/user.png')}}" alt="Profile Image"/></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"> <img src="{{asset('assets/images/user.png')}}"
                                                          alt="Profile Image"/></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"> <img src="{{asset('assets/images/user.png')}}"
                                                          alt="Profile Image"/></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <div class="text-center">
                                <a>
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->